name: Deploy WebGL to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true # リポジトリ履歴を汚さないためにLFSは無効化

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 100MB超のビルドファイルごと直接Pagesへ成果物としてアップロード
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # index.htmlやBuildフォルダがあるルートを指定

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
